"""
tests/test_fusion_real.py

M9 Fusion verified on REAL M8 branch checkpoints + REAL M6 windows
(not the stub encoder used in tests/test_fusion.py).

Skips cleanly if the 20 M8 checkpoints or the M6 window files are not
present in this environment (they are gitignored artifacts pulled from
the kaggle-checkpoints branch / regenerated by M6).
"""

from __future__ import annotations

import numpy as np
import pytest
import torch

from src.models.fusion import FusionModule
from src.models.ts2vec_wrapper import TS2VecBranch
from src.utils.config import load_config
from src.utils.paths import BASE_CONFIG_PATH, CHECKPOINTS_DIR, DATA_PROCESSED_DIR

CPU = torch.device("cpu")
SEED = 42
TFS = ("15m", "1h", "4h", "1d")
N = 40  # small slice of real windows for speed

CONDITIONS = {
    "1TF": ["1h"], "2TF": ["15m", "1h"], "3TF": ["15m", "1h", "4h"],
    "4TF": ["15m", "1h", "4h", "1d"], "BL-15m": ["15m"], "BL-4h": ["4h"], "BL-1d": ["1d"],
}


def _have_assets() -> bool:
    ck = all((CHECKPOINTS_DIR / f"branch_{tf}" / f"seed_{SEED}" / "best_model.pt").exists() for tf in TFS)
    wd = all((DATA_PROCESSED_DIR / f"test_windows_{tf}.npy").exists() for tf in TFS)
    return ck and wd


pytestmark = pytest.mark.skipif(
    not _have_assets(),
    reason="real M8 checkpoints / M6 windows not present (pull kaggle-checkpoints + run M6)",
)


@pytest.fixture(scope="module")
def real_branch_embeddings() -> dict[str, np.ndarray]:
    """Encode a real test-window slice with the real seed-42 branch encoders."""
    cfg = load_config(BASE_CONFIG_PATH)
    out: dict[str, np.ndarray] = {}
    for tf in TFS:
        branch = TS2VecBranch(cfg, tf, CPU)
        branch.load_checkpoint(CHECKPOINTS_DIR / f"branch_{tf}" / f"seed_{SEED}" / "best_model.pt")
        windows = np.load(DATA_PROCESSED_DIR / f"test_windows_{tf}.npy")[:N]
        out[tf] = branch.encode(windows)
    return out


class TestRealBranchEncode:
    def test_branch_embeddings_shape_and_finite(self, real_branch_embeddings) -> None:
        for tf, emb in real_branch_embeddings.items():
            assert emb.shape == (N, 64), tf
            assert emb.dtype == np.float32
            assert np.isfinite(emb).all(), tf

    def test_branch_encode_deterministic(self) -> None:
        cfg = load_config(BASE_CONFIG_PATH)
        branch = TS2VecBranch(cfg, "1h", CPU)
        branch.load_checkpoint(CHECKPOINTS_DIR / "branch_1h" / f"seed_{SEED}" / "best_model.pt")
        w = np.load(DATA_PROCESSED_DIR / "test_windows_1h.npy")[:N]
        np.testing.assert_array_equal(branch.encode(w), branch.encode(w))


class TestRealFusion:
    @pytest.mark.parametrize("condition", list(CONDITIONS))
    def test_fused_is_n_by_256_finite(self, condition, real_branch_embeddings) -> None:
        module = FusionModule(condition, CONDITIONS[condition])
        fused = module.fuse(real_branch_embeddings)
        assert fused.shape == (N, 256)
        assert fused.dtype == np.float32
        assert np.isfinite(fused).all()

    def test_fusion_deterministic_real(self, real_branch_embeddings) -> None:
        a = FusionModule("4TF", CONDITIONS["4TF"], projection_seed=42).fuse(real_branch_embeddings)
        b = FusionModule("4TF", CONDITIONS["4TF"], projection_seed=42).fuse(real_branch_embeddings)
        np.testing.assert_array_equal(a, b)

    def test_conditions_differ_from_each_other(self, real_branch_embeddings) -> None:
        # Different conditions (different active branches) -> different fused output.
        f1 = FusionModule("1TF", CONDITIONS["1TF"]).fuse(real_branch_embeddings)
        f4 = FusionModule("4TF", CONDITIONS["4TF"]).fuse(real_branch_embeddings)
        assert not np.allclose(f1, f4)
